Repository IGNF/geopf-extensions-openlayers, pull requests merged in 2024-12, with the labels that each got.

#291 fix(dsfr)(advanced-search): le Panneau ne s'affiche pas correctement
  package.json
  src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css
Labels: bug

#290 Fix: Utilisation de l'attribut data-url pour charger la configuration
  samples-src/pages/tests/Default/pages-ol-bundle-data-url.html
  samples-src/resources/data/configuration/sample.json
  src/packages/Utils/AutoLoadConfig.js
  src/packages/bundle.js
Labels: bug

#294 ajout CLASSNAME pour tous les widgets
  snippets/widgets/Controls/WidgetEntries/widget.js
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/ControlList/ControlList.js
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/Export/Export.js
  src/packages/Controls/FullScreen/GeoportalFullScreen.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Controls/Legends/Legends.js
  src/packages/Controls/LocationSelector/LocationSelector.js
  src/packages/Controls/MousePosition/MousePosition.js
  src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
  src/packages/Controls/ReverseGeocode/ReverseGeocode.js
  src/packages/Controls/Route/Route.js
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Controls/Territories/Territories.js
Labels: enhancement

#296 fix(drawing): Titre par défaut à la couche du croquis
  DRAFT_CHANGELOG.md
  package.json
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
  src/packages/Controls/Route/Route.js
Labels: bug

#300 feat(controlList): add controllist widget for classic mode
  package.json
  samples-src/pages/tests/Default/pages-ol-modules-default.html
  samples-src/pages/tests/Default/pages-ol-modules-dsfr-default.html
  src/packages/CSS/Controls/ControlList/DSFRcontrolListStyle.css
  src/packages/CSS/Controls/ControlList/GPFcontrolList.css
  src/packages/CSS/Controls/ControlList/GPFcontrolListStyle.css
  src/packages/CSS/Controls/ControlList/img/close.png
  src/packages/Controls/ControlList/ControlListDOM.js
Labels: enhancement

#305 feat(reverse): limite les zones dessinnées par rapport aux limites du service
  package.json
  src/packages/Controls/ReverseGeocode/ReverseGeocode.js
Labels: enhancement

#301 feat(gfi): pas d'affichage du tout si pas de données sous le clic
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
Labels: enhancement

#311 feat(search) : Options pour améliorer l'affichage des résultats d'autocompletion
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-filter-duplicate.html
  src/packages/Controls/SearchEngine/SearchEngine.js
Labels: enhancement

#313 Correction sur la pop-up affichée au clic des markers du searchEngine
  DRAFT_CHANGELOG.md
  package.json
  src/packages/CSS/Controls/Drawing/DSFRdrawingStyle.css
  src/packages/Controls/SearchEngine/SearchEngine.js
Labels: enhancement, dsfr
