Repository IGNF/geopf-extensions-openlayers, pull requests merged in 2024-10, with the labels that each got.

#180 Fix(territories): corrections sur le widget territories
  package.json
  src/packages/Controls/Territories/Territories.json
  src/packages/Controls/Territories/TerritoriesDOM.js
Labels: bug

#182 Fix/recette mouseposition
  package.json
  src/packages/CSS/Controls/MousePosition/DSFRmousePositionStyle.css
  src/packages/Controls/MousePosition/MousePosition.js
  src/packages/Controls/MousePosition/MousePositionDOM.js
Labels: bug

#184 Fix(Territory): le widget est responsive
  src/packages/CSS/Controls/Territories/DSFRterritoriesStyle.css
  src/packages/Controls/Territories/Territories.js
Labels: bug, dsfr

#170 doc(widgets): Mise à jour de la documentation pour les widgets
  DRAFT_CHANGELOG.md
  doc/.markdownlint.json
  doc/DOCUMENTATION.md
  package.json
Labels: doc

#186 fix(mousePosition): liste déroulante draggable true
  package.json
  src/packages/Controls/MousePosition/MousePosition.js
Labels: bug

#187 fix(panels): ajoute libellé "fermer" aux panels à entete
  package.json
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Controls/Legends/LegendsDOM.js
Labels: dsfr

#185 fix(ls)(dsfr)(mobile): fullscreen et généralisation du comportement
  package.json
  samples-src/pages/tests/Default/pages-ol-modules-dsrf-default.html
  src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
  src/packages/CSS/Controls/Territories/DSFRterritoriesStyle.css
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Controls/Territories/TerritoriesDOM.js
Labels: enhancement, dsfr

#189 fix(ls): mauvaise orthographe pour le mot zoomer
  package.json
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
Labels: bug

#193 fix(terr:css): retrait important pour surcharge hauteur cote entree carto
  package.json
  src/packages/CSS/Controls/Territories/DSFRterritoriesStyle.css
Labels: bug

#196 feat(dsfr): widget btns now secondary instead of primary
  package.json
  samples-src/pages/tests/MousePosition/pages-ol-mouseposition-modules-dsfr-default.html
  src/packages/CSS/Controls/Catalog/DSFRcatalogStyle.css
  src/packages/CSS/Controls/Drawing/DSFRdrawingStyle.css
  src/packages/CSS/Controls/ElevationPath/DSFRelevationPathStyle.css
  src/packages/CSS/Controls/FullScreen/DSFRfullScreenStyle.css
  src/packages/CSS/Controls/GetFeatureInfo/DSFRgetFeatureInfoStyle.css
  src/packages/CSS/Controls/Isochron/DSFRisochronStyle.css
  src/packages/CSS/Controls/LayerImport/DSFRlayerImportStyle.css
  src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
  src/packages/CSS/Controls/Legends/DSFRlegendsStyle.css
  src/packages/CSS/Controls/Measures/DSFRmeasureAreaStyle.css
  src/packages/CSS/Controls/Measures/DSFRmeasureAzimuthStyle.css
  src/packages/CSS/Controls/Measures/DSFRmeasureLengthStyle.css
  src/packages/CSS/Controls/MousePosition/DSFRmousePositionStyle.css
  src/packages/CSS/Controls/OverviewMap/DSFRoverviewMapStyle.css
  src/packages/CSS/Controls/ReverseGeocoding/DSFRreverseGeocodingStyle.css
  src/packages/CSS/Controls/Route/DSFRrouteStyle.css
  src/packages/CSS/Controls/Territories/DSFRterritoriesStyle.css
  src/packages/CSS/Controls/Zoom/DSFRzoomStyle.css
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/Catalog/CatalogDOM.js
  src/packages/Controls/Drawing/DrawingDOM.js
  src/packages/Controls/ElevationPath/ElevationPathDOM.js
  src/packages/Controls/FullScreen/GeoportalFullScreen.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
  src/packages/Controls/Isocurve/IsocurveDOM.js
  src/packages/Controls/LayerImport/LayerImportDOM.js
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Controls/Legends/LegendsDOM.js
  src/packages/Controls/Measures/MeasureAreaDOM.js
  src/packages/Controls/Measures/MeasureAzimuthDOM.js
  src/packages/Controls/Measures/MeasureLengthDOM.js
  src/packages/Controls/MousePosition/MousePositionDOM.js
  src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
  src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
  src/packages/Controls/Route/RouteDOM.js
  src/packages/Controls/Territories/TerritoriesDOM.js
  src/packages/Controls/Zoom/GeoportalZoom.js
Labels: dsfr

#197 feat(SearcEngine): Ajout de l'option markerUrl
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html
  src/packages/Controls/SearchEngine/SearchEngine.js
Labels: enhancement

#169 refactor(GFI): Évolution du widget GFI
  .eslintrc
  DRAFT_CHANGELOG.md
  samples-src/pages/tests/Default/pages-ol-modules-dsrf-default.html
  samples-src/pages/tests/GetFeatureInfo/pages-ol-getfeatureinfo-modules-default.html
  samples-src/pages/tests/GetFeatureInfo/pages-ol-getfeatureinfo-modules-options-dsfr.html
  samples-src/pages/tests/GetFeatureInfo/pages-ol-getfeatureinfo-modules-options.html
  snippets/widgets/Controls/WidgetEntries/widget.js
  snippets/widgets/Controls/WidgetForm/widget.js
  src/packages/CSS/Controls/GetFeatureInfo/DSFRgetFeatureInfoStyle.css
  src/packages/CSS/Controls/GetFeatureInfo/GPFgetFeatureInfo.css
  src/packages/CSS/Controls/GetFeatureInfo/GPFgetFeatureInfoStyle.css
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
  src/packages/Controls/Utils/AsyncData.js
Labels: enhancement, dsfr

#211 refacto(getFeatureInfo): récuperation du layer title sans utilisation de la configuration
  package.json
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
Labels: enhancement

#209 feat(catalog): Passage du widget au thème Classic
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/Catalog/pages-ol-catalog-modules-categories-1.html
  samples-src/pages/tests/Catalog/pages-ol-catalog-modules-categories-2.html
  samples-src/pages/tests/Catalog/pages-ol-catalog-modules-categories-3.html
  samples-src/pages/tests/Catalog/pages-ol-catalog-modules-default.html
  samples-src/pages/tests/LayerImport/pages-ol-layerimport-modules-default.html
  samples-src/pages/tests/LayerImport/pages-ol-layerimport-modules-dsfr-default.html
  src/packages/CSS/Controls/Catalog/GPFcatalogStyle.css
  src/packages/CSS/Controls/Catalog/img/GPcatalogOpen.png
  src/packages/CSS/Controls/Catalog/img/GPcatalogTools.png
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/Catalog/CatalogDOM.js
Labels: enhancement

#214 feat(search): wmts layers priority
  package.json
  samples-src/pages/tests/Drawing/pages-ol-drawing-modules-dsfr-default.html
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html
  src/packages/Services/Search.js
Labels: enhancement

#219 fix(chrome): boutons activés
  package.json
  src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/Catalog/CatalogDOM.js
  src/packages/Controls/Drawing/DrawingDOM.js
  src/packages/Controls/ElevationPath/ElevationPathDOM.js
  src/packages/Controls/FullScreen/GeoportalFullScreen.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
  src/packages/Controls/Isocurve/IsocurveDOM.js
  src/packages/Controls/LayerImport/LayerImportDOM.js
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Controls/Legends/LegendsDOM.js
  src/packages/Controls/Measures/MeasureAreaDOM.js
  src/packages/Controls/Measures/MeasureAzimuthDOM.js
  src/packages/Controls/Measures/MeasureLengthDOM.js
  src/packages/Controls/MousePosition/MousePositionDOM.js
  src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
  src/packages/Controls/Route/RouteDOM.js
  src/packages/Controls/Territories/TerritoriesDOM.js
  src/packages/Controls/Zoom/GeoportalZoom.js
Labels: bug

#236 gestion des panels des widgets : 1 ouvert par côté
  snippets/widgets/Controls/WidgetEntries/widget.js
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/Catalog/CatalogDOM.js
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/ElevationPath/ElevationPath.js
  src/packages/Controls/Export/Export.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Controls/LayerImport/LayerImportDOM.js
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Controls/Legends/Legends.js
  src/packages/Controls/Legends/LegendsDOM.js
  src/packages/Controls/Measures/MeasureArea.js
  src/packages/Controls/Measures/MeasureAzimuth.js
  src/packages/Controls/Measures/MeasureLength.js
  src/packages/Controls/Measures/Measures.js
  src/packages/Controls/MousePosition/MousePosition.js
  src/packages/Controls/MousePosition/MousePositionDOM.js
  src/packages/Controls/ReverseGeocode/ReverseGeocode.js
  src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
  src/packages/Controls/Route/Route.js
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Controls/SearchEngine/SearchEngineDOM.js
  src/packages/Controls/Territories/Territories.js
  src/packages/Controls/Territories/TerritoriesDOM.js
  src/packages/Controls/Widget.js
  src/packages/Utils/PanelManager.js
Labels: enhancement, dsfr

#237 fix gfi close panels with panel manager
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
Labels: bug
