Repository IGNF/geopf-extensions-openlayers, pull requests merged in 2024-11, with the labels that each got.

#238 refactor(doc): update readme
  doc/DOCUMENTATION.md
Labels: doc

#250 fix(LayerImport): Afficher le bouton retour sur la fenêtre des résultats
  package.json
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Utils/PanelManager.js
Labels: bug

#251 fix(LayerImport): Gestion des GeoJSON avec des géométries nulles
  package.json
  src/packages/Formats/Styling.js
Labels: bug

#257 fix(scalebar): surcharge ol pour passer l'echelle sous les tooltips
  package.json
  samples-src/pages/tests/Default/pages-ol-modules-dsrf-default.html
  src/packages/CSS/DSFRgeneralWidget.css
Labels: bug, dsfr

#256 fix(alti-profile): #247 saisie ppossible sous la fenêtre de résultats
  package.json
  src/packages/CSS/Controls/ElevationPath/DSFRelevationPathStyle.css
Labels: bug

#258 feat(search): info attributaires sur le marker de geolocalisation (#244)
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/ReverseGeocode/ReverseGeocode.js
  src/packages/Controls/Route/Route.js
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Controls/Utils/Gfi.js
Labels: enhancement, dsfr

#263 fix(gfi): retrait d'une scrollbar horizontale inutile (#253)
  package.json
  src/packages/CSS/Controls/GetFeatureInfo/GPFgetFeatureInfo.css
  src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
Labels: dsfr

#267 fix(Search): Amélioration de la recherche
  package.json
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-options.html
  samples-src/pages/tests/Services/pages-ol-searchservice-modules-default.html
  src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/Catalog/CatalogDOM.js
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Controls/SearchEngine/SearchEngineDOM.js
  src/packages/Layers/SourceWFS.js
  src/packages/Layers/SourceWMS.js
  src/packages/Layers/SourceWMTS.js
  src/packages/Services/Search.js
Labels: bug

#268 Feat(button): passage des boutons en tertiary et ajout d'une option pour les réunir
  package.json
  samples-src/pages/tests/Default/pages-ol-modules-dsfr-default.html
  samples-src/pages/tests/Default/pages-ol-modules-dsfr-grouped-buttons-default.html
  snippets/widgets/Controls/WidgetEntries/widget.js
  snippets/widgets/Controls/WidgetForm/widget.js
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/Catalog/CatalogDOM.js
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/Drawing/DrawingDOM.js
  src/packages/Controls/ElevationPath/ElevationPath.js
  src/packages/Controls/ElevationPath/ElevationPathDOM.js
  src/packages/Controls/FullScreen/GeoportalFullScreen.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/Isocurve/IsocurveDOM.js
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Controls/LayerImport/LayerImportDOM.js
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Controls/Legends/Legends.js
  src/packages/Controls/Legends/LegendsDOM.js
  src/packages/Controls/Measures/MeasureArea.js
  src/packages/Controls/Measures/MeasureAreaDOM.js
  src/packages/Controls/Measures/MeasureAzimuth.js
  src/packages/Controls/Measures/MeasureAzimuthDOM.js
  src/packages/Controls/Measures/MeasureLength.js
  src/packages/Controls/Measures/MeasureLengthDOM.js
  src/packages/Controls/MousePosition/MousePosition.js
  src/packages/Controls/MousePosition/MousePositionDOM.js
  src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
  src/packages/Controls/ReverseGeocode/ReverseGeocode.js
  src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
  src/packages/Controls/Route/Route.js
  src/packages/Controls/Route/RouteDOM.js
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Controls/Territories/Territories.js
  src/packages/Controls/Territories/TerritoriesDOM.js
  src/packages/Controls/Zoom/GeoportalZoom.js
Labels: new feature, dsfr

#272 feat(controlList): add controllist widget
  build/webpack/controls.webpack.config.js
  build/webpack/extend.themes.webpack.js
  build/webpack/modules.webpack.config.js
  package.json
  samples-src/pages/tests/Default/pages-ol-modules-dsfr-default.html
  samples-src/templates/packages/ol-sample-bundle-dsfr-layout.hbs
  samples-src/templates/packages/ol-sample-modules-dsfr-layout.hbs
  src/index.js
  src/packages/CSS/Controls/ControlList/DSFRcontrolListStyle.css
  src/packages/CSS/Controls/ControlList/GPFcontrolList.css
  src/packages/CSS/Controls/ControlList/GPFcontrolListStyle.css
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/Control.js
  src/packages/Controls/ControlList/ControlList.js
  src/packages/Controls/ControlList/ControlListDOM.js
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/ElevationPath/ElevationPath.js
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
  src/packages/Controls/Legends/Legends.js
  src/packages/Controls/Measures/MeasureArea.js
  src/packages/Controls/Measures/MeasureAzimuth.js
  src/packages/Controls/Measures/MeasureLength.js
  src/packages/Controls/MousePosition/MousePosition.js
  src/packages/Controls/ReverseGeocode/ReverseGeocode.js
  src/packages/Controls/Route/Route.js
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Controls/Territories/Territories.js
  src/packages/bundle.js
Labels: new feature

#281 fix(controlList): plante si controle sans dialog listable
  package.json
  samples-src/pages/tests/Default/pages-ol-modules-dsfr-default.html
  src/packages/Controls/ControlList/ControlListDOM.js
Labels: bug

#279 fix(overview)(dsfr)(css): activated status
  package.json
  src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
  src/packages/CSS/Controls/OverviewMap/DSFRoverviewMapStyle.css
  src/packages/Controls/ControlList/ControlListDOM.js
Labels: bug, dsfr

#288 Feat/dsfr drawing
  src/packages/CSS/Controls/Drawing/DSFRdrawingStyle.css
  src/packages/CSS/Controls/Drawing/GPFdrawing.css
  src/packages/CSS/Controls/Drawing/GPFdrawingStyle.css
  src/packages/CSS/Controls/Drawing/img/dsfr/create-label.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/create-line.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/create-point.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/create-polygon.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/delete.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/edit-geom.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/edit-style.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/edit-text.svg
  src/packages/Controls/Drawing/DrawingDOM.js
Labels: enhancement, dsfr
