Repository IGNF/geopf-extensions-openlayers, pull requests merged in 2025-06, with the labels that each got.

#382 fix(ls): greyscale vectortiles after style switch
  DRAFT_CHANGELOG.md
  package.json
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
Labels: bug

#383 ui(buttons): new style
  DRAFT_CHANGELOG.md
  core.js
  package.json
  src/packages/CSS/Controls/Zoom/DSFRzoomStyle.css
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/someControl.js
  src/packages/Utils/LayerConfigUtils.js
  src/packages/anotherWidget.js
  src/packages/controlsUtils.js
  src/packages/exampleWidget.js
  utils.js
  widgetTemplate.js
Labels: enhancement

#386 ui: ombre des boutons
  package.json
  src/packages/CSS/DSFRgeneralWidget.css
Labels: dsfr

#389 feat(layerswitcher) : Ajout méthodes forget & listen sur l'écouteur d'ajout de couche
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/Drawing/pages-ol-drawing-modules-dsfr-forget-listen.html
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
Labels: enhancement

#392 feat(Reporting): creation nouveau widget de signalement d'anomalies
  DRAFT_CHANGELOG.md
  build/webpack/controls.webpack.config.js
  build/webpack/extend.themes.webpack.js
  build/webpack/modules.webpack.config.js
  package.json
  samples-src/pages/tests/Default/pages-ol-bundle-dsfr-default.html
  samples-src/pages/tests/Default/pages-ol-modules-dsfr-default.html
  samples-src/pages/tests/Reporting/pages-ol-reporting-modules-ioc-form-dsfr.html
  samples-src/pages/tests/Reporting/pages-ol-reporting-modules-ioc-input-dsfr.html
  samples-src/pages/tests/Reporting/pages-ol-reporting-modules-ioc-service-dsfr.html
  samples-src/pages/tests/Reporting/pages-ol-reporting-modules-options-dsfr.html
  samples-src/resources/reporting/iocForm.js
  samples-src/resources/reporting/iocInput.js
  samples-src/resources/reporting/iocService.js
  snippets/widgets/Controls/WidgetForm/widgetDOM.js
  src/index.js
  src/packages/CSS/Controls/Reporting/DSFRreportingStyle.css
  src/packages/CSS/Controls/Reporting/GPFreporting.css
  src/packages/CSS/Controls/Reporting/GPFreportingStyle.css
  src/packages/CSS/Controls/Reporting/img/dsfr/collapse.svg
  src/packages/CSS/Controls/Reporting/img/dsfr/header-reporting.svg
  src/packages/CSS/Controls/Reporting/img/dsfr/header-return.svg
  src/packages/CSS/Controls/Reporting/img/dsfr/reporting.svg
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/Reporting/Reporting.js
  src/packages/Controls/Reporting/ReportingDOM.js
  src/packages/bundle.js
Labels: new feature
