Repository IGNF/geopf-extensions-openlayers, pull requests merged in 2025-07, with the labels that each got.

#401 feat(Catalogue): Mise en conformité du widget
  package.json
  samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-categories-1.html
  samples-src/resources/data/mapbox/styles/osm-etranger.json
  src/packages/CSS/Controls/Catalog/DSFRcatalogStyle.css
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/Catalog/CatalogDOM.js
  src/packages/Controls/Catalog/topics.json
  src/packages/Controls/Reporting/Reporting.js
  src/packages/Controls/Reporting/ReportingDOM.js
Labels: enhancement, dsfr

#407 fix(mousePosition): fonction d'edition des coordonnées
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/MousePosition/pages-ol-mouseposition-modules-dsfr-editcoordinates.html
  src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
  src/packages/CSS/Controls/MousePosition/DSFRmousePositionStyle.css
  src/packages/CSS/Controls/MousePosition/GPFmousePosition.css
  src/packages/CSS/Controls/MousePosition/GPFmousePositionStyle.css
  src/packages/CSS/Controls/MousePosition/img/dsfr/arrow-go-back-fill.svg
  src/packages/CSS/Controls/MousePosition/img/dsfr/edit.svg
  src/packages/CSS/Controls/MousePosition/img/dsfr/map-pin-2-fill.svg
  src/packages/Controls/MousePosition/MousePositionDOM.js
Labels: bug, enhancement, dsfr

#411 fix(compute) : Reduction du nombre de chiffres significatifs des coordonnées envoyéspour les requêtes itinéraires et isochrones
  DRAFT_CHANGELOG.md
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/Route/Route.js
Labels: enhancement

#417 fix(layerswitcher): display none edit en mode mobile si pas dispo
  DRAFT_CHANGELOG.md
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
Labels: bug

#419 fix(css/dsfr): tooltips moches sur control list et zoom out
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/Default/pages-ol-modules-dsfr-default.html
  src/packages/CSS/Controls/ControlList/DSFRcontrolListStyle.css
  src/packages/CSS/Controls/Zoom/DSFRzoomStyle.css
Labels: bug

#420 feat(LayerSwitcher) : Mise en place de tooltips HTML
  DRAFT_CHANGELOG.md
  doc/NOTE-LAYERSWITCHER.md
  package.json
  samples-src/pages/tests/LayerSwitcher/pages-ol-layerswitcher-modules-dsfr-tooltips.html
  samples-src/resources/data/configuration/config-catalog.json
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Utils/ToolTips.js
Labels: new feature
