Repository IGNF/geopf-extensions-openlayers, pull requests merged in 2025-01, with the labels that each got.

#316 Fix : correction du comportement et du style des boutons de retours
  DRAFT_CHANGELOG.md
  package.json
  src/packages/CSS/Controls/LayerImport/DSFRlayerImportStyle.css
  src/packages/CSS/Controls/LayerImport/GPFlayerImportStyle.css
  src/packages/CSS/Controls/ReverseGeocoding/GPFreverseGeocodingStyle.css
  src/packages/CSS/Controls/ReverseGeocoding/img/GPreverseGeocodingReturn.png
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/CSS/GPFgeneralWidget.css
  src/packages/CSS/img/GPreturn.png
  src/packages/CSS/img/GPreturnDSFR.png
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Controls/LayerImport/LayerImportDOM.js
  src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
Labels: bug, dsfr

#317 feat(measures): ajout option pour forcer unité d'affichage
  DRAFT_CHANGELOG.md
  package.json
  src/packages/Controls/Measures/MeasureLength.js
Labels: enhancement

#326 Ajout import geoportal-access-lib sur SourceWFS
  src/packages/Layers/SourceWFS.js
Labels: bug

#320 fix(LayerSwitcher) : Zoom sur l'étendu du format MapBox importé
  DRAFT_CHANGELOG.md
  build/webpack/bundle.webpack.config.js
  build/webpack/modules.webpack.config.js
  package.json
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
Labels: bug

#327 chore(doc): ajout de la documentation de contribution et compilation
  COMPILE.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
Labels: doc

#328 feat(drawing): better UX
  package.json
  src/packages/CSS/Controls/Drawing/DSFRdrawingStyle.css
  src/packages/CSS/Controls/Drawing/GPFdrawing.css
  src/packages/CSS/Controls/Drawing/GPFdrawingStyle.css
  src/packages/CSS/Controls/Drawing/img/dsfr/create-line.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/create-point.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/edit-geom.svg
  src/packages/CSS/Controls/Drawing/img/dsfr/edit-text.svg
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/Drawing/DrawingDOM.js
Labels: enhancement, dsfr

#306 fix(mapbox) : choix sur le param declutter
  samples-src/pages/tests/Layers/pages-ol-layermapbox-modules-conf.html
  samples-src/resources/vendor/ol/v10.3.1/ol.d.ts
  samples-src/resources/vendor/ol/v10.3.1/ol.d.ts.map
  src/packages/Controls/Catalog/Catalog.js
  src/packages/Controls/SearchEngine/SearchEngine.js
Labels: enhancement

#329 menu contextuel clic droit
  DRAFT_CHANGELOG.md
  build/webpack/controls.webpack.config.js
  build/webpack/extend.themes.webpack.js
  build/webpack/modules.webpack.config.js
  package.json
  samples-src/pages/tests/ContextMenu/pages-ol-modules-contextmenu-dsfr.html
  samples-src/pages/tests/ContextMenu/pages-ol-modules-contextmenu.html
  src/index.js
  src/packages/CSS/Controls/ContextMenu/DSFRcontextMenuStyle.css
  src/packages/CSS/Controls/ContextMenu/GPFcontextMenu.css
  src/packages/CSS/Controls/ContextMenu/GPFcontextMenuStyle.css
  src/packages/Controls/ContextMenu/ContextMenu.js
  src/packages/Controls/ContextMenu/ContextMenuDOM.js
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/Route/Route.js
  src/packages/bundle.js
Labels: new feature

#333 css fix adresse et coord
  DRAFT_CHANGELOG.md
  package.json
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/ContextMenu/ContextMenuDOM.js
Labels: bug

#340 fix(contextmenu): bugs
  src/packages/Controls/ContextMenu/ContextMenu.js
  src/packages/Controls/ContextMenu/ContextMenuDOM.js
  src/packages/Controls/Route/Route.js
Labels: enhancement

#342 feat(layerswitcher): Ajout d'un bouton d'édition des croquis (ou des données de type vecteur)
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/Drawing/pages-ol-drawing-modules-dsfr-edition.html
  samples-src/pages/tests/LayerSwitcher/pages-ol-layerswitcher-modules-dsfr-edition.html
  src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
  src/packages/CSS/Controls/LayerSwitcher/GPFlayerSwitcherStyle.css
  src/packages/CSS/Controls/LayerSwitcher/img/dsfr/edit.svg
  src/packages/Controls/Drawing/Drawing.js
  src/packages/Controls/ElevationPath/ElevationPath.js
  src/packages/Controls/Isocurve/Isocurve.js
  src/packages/Controls/LayerImport/LayerImport.js
  src/packages/Controls/LayerSwitcher/LayerSwitcher.js
  src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
  src/packages/Controls/Route/Route.js
Labels: new feature, dsfr
