Repository IGNF/geopf-extensions-openlayers, pull requests merged in 2025-02, with the labels that each got.

#346 feat(search)(dsfr): change default mode to not splitted. change not splitted style. sets advanced search as button (again)
  package.json
  src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css
  src/packages/CSS/Controls/SearchEngine/GPFsearchEngine.css
  src/packages/CSS/Controls/SearchEngine/GPFsearchEngineStyle.css
  src/packages/CSS/Controls/SearchEngine/img/dsfr/catalogue.svg
  src/packages/CSS/Controls/SearchEngine/img/dsfr/lieux-adresses.svg
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Controls/SearchEngine/SearchEngineDOM.js
Labels: dsfr

#349 Fix(LocationSelector/LayerImport) : Corrections sur la taille des fenêtres de résultats d'imports et d'autocomplétion
  DRAFT_CHANGELOG.md
  package.json
  src/packages/CSS/Controls/LayerImport/DSFRlayerImportStyle.css
  src/packages/CSS/Controls/LayerImport/GPFlayerImport.css
  src/packages/CSS/Controls/LayerImport/GPFlayerImportStyle.css
  src/packages/CSS/Controls/LocationSelector/DSFRlocationStyle.css
  src/packages/CSS/Controls/LocationSelector/GPFlocation.css
  src/packages/CSS/Controls/LocationSelector/GPFlocationStyle.css
  src/packages/CSS/Controls/ReverseGeocoding/DSFRreverseGeocodingStyle.css
  src/packages/CSS/Controls/SearchEngine/GPFsearchEngineStyle.css
  src/packages/CSS/DSFRgeneralWidget.css
  src/packages/Controls/LocationSelector/LocationSelectorDOM.js
Labels: bug, dsfr

#352 Feature/filter layers search by config
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Services/Search.js
Labels: enhancement

#353 feat(searchEngine): ajout d'un filtre par projection des données
  DRAFT_CHANGELOG.md
  package.json
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html
  src/packages/Controls/SearchEngine/SearchEngine.js
Labels: enhancement

#357 fix(gfi): retrait de propriétés liées aux labels dans la fenetre gfi
  DRAFT_CHANGELOG.md
  package.json
  src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
  src/packages/Controls/Utils/Gfi.js
Labels: bug

#358 feat(search): filtrage layers sur name + service
  DRAFT_CHANGELOG.md
  package.json
  samples-src/config.json
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html
  samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-options.html
  samples-src/pages/tests/Services/pages-ol-searchservice-modules-default.html
  src/packages/Controls/SearchEngine/SearchEngine.js
  src/packages/Services/Search.js
Labels: enhancement
